# Generated by Django 2.0.3 on 2018-04-05 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
